---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      include_vars: vars/main.yml

    - name: Verify asdf was installed
      include_tasks: "../common/tasks/verify_asdf.yml"
