---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    ansible_os_family: "Darwin"
    version_command: "ruby --version"
  tasks:

    - name: Load Scenario Variables
      include_vars: vars/main.yml

    - name: Verify asdf was installed
      include_tasks: "../common/tasks/verify_asdf.yml"

    - name: Verify the correct plugin was installed
      include_tasks: "../common/tasks/verify_plugin.yml"

    - name: Verify the correct version was Installed
      include_tasks: "../common/tasks/verify_binary.yml"
