---
- name: Set vars
  set_fact:
    asdf_nodejs_keyring: "{{ asdf_user_home }}/.asdf/keyrings/nodejs"

- name: Check if Node.js Keyring already exists
  become: True
  become_user: "{{ asdf_user }}"
  stat:
    path: "{{ asdf_nodejs_keyring }}"
  register: asdf_nodejs_keyring_path

- name: Create Keyring for Node.js Keys
  become: True
  become_user: "{{ asdf_user }}"
  file:
    path: "{{ asdf_nodejs_keyring }}"
    state: directory
    owner: "{{ asdf_user }}"
    mode: 0700
  when: not asdf_nodejs_keyring_path.stat.exists

- name: Import Node.js Keys to Keyring
  become: True
  become_user: "{{ asdf_user }}"
  command: "bash -lc '{{ asdf_user_home }}/.asdf/plugins/nodejs/bin/import-release-team-keyring'"
  args:
    creates: "{{ asdf_nodejs_keyring }}/pubring.gpg"
  environment:
    GNUPGHOME: "{{ asdf_nodejs_keyring }}"
  when: not asdf_nodejs_keyring_path.stat.exists
